-- KHUSHALI JEWELLS ERP v704 - SAFE SPLIT-STATE RECOVERY + LIVE SYNC CORE
-- Run once in Supabase Dashboard > SQL Editor before publishing v704.
-- This migration preserves public.erp_state, backs up both cloud representations,
-- restores v703 compatibility long enough to drain queued changes, and keeps the
-- normalized tables aligned with the newer compatibility row.

alter role anon set statement_timeout = '60s';
alter role authenticated set statement_timeout = '60s';

create table if not exists public.erp_sync_signal (
  id text primary key,
  updated_at timestamptz not null default clock_timestamp(),
  app_version text not null default 'unknown'
);

create table if not exists public.erp_state_backups (
  id text primary key,
  state_id text not null,
  backup_key text not null,
  backup_kind text not null check (backup_kind in ('version-upgrade', 'daily', 'manual')),
  source_version text not null default 'unknown',
  target_version text not null default 'unknown',
  source_updated_at timestamptz,
  profile jsonb not null default '{}'::jsonb,
  data jsonb not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (state_id, backup_key)
);

create table if not exists public.erp_entity_meta (
  state_id text primary key,
  revision bigint not null default 0,
  legacy_revision bigint not null default 0,
  minimum_revision bigint not null default 0,
  updated_at timestamptz not null default clock_timestamp(),
  app_version text not null default 'unknown',
  legacy_source_updated_at timestamptz
);

alter table public.erp_entity_meta
  add column if not exists legacy_source_updated_at timestamptz;

create table if not exists public.erp_entity_records (
  state_id text not null,
  collection text not null,
  record_id text not null,
  data jsonb,
  deleted boolean not null default false,
  revision bigint not null default 0,
  updated_at timestamptz not null default clock_timestamp(),
  operation_id text,
  primary key (state_id, collection, record_id)
);

create table if not exists public.erp_entity_changes (
  id bigint generated by default as identity primary key,
  state_id text not null,
  revision bigint not null,
  collection text not null,
  record_id text not null,
  operation text not null check (operation in ('upsert', 'delete')),
  data jsonb,
  updated_at timestamptz not null default clock_timestamp(),
  operation_id text,
  device_id text,
  user_name text,
  app_version text not null default 'unknown',
  unique (state_id, revision, collection, record_id)
);

create table if not exists public.erp_entity_operations (
  state_id text not null,
  operation_id text not null,
  revision bigint not null,
  legacy_revision bigint not null default 0,
  saved_at timestamptz not null default clock_timestamp(),
  device_id text,
  user_name text,
  app_version text not null default 'unknown',
  primary key (state_id, operation_id)
);

create table if not exists public.erp_serial_counters (
  state_id text not null,
  serial_kind text not null check (serial_kind in ('job', 'production', 'lot', 'bill')),
  next_value bigint not null,
  updated_at timestamptz not null default clock_timestamp(),
  last_device_id text,
  app_version text not null default 'unknown',
  primary key (state_id, serial_kind)
);

create table if not exists public.erp_backup_requests (
  state_id text not null,
  backup_key text not null,
  requested_at timestamptz not null default clock_timestamp(),
  completed_at timestamptz,
  app_version text not null default 'unknown',
  status text not null default 'pending' check (status in ('pending', 'complete', 'failed')),
  error_detail text,
  primary key (state_id, backup_key)
);

alter table public.erp_sync_signal
  add column if not exists revision bigint not null default 0,
  add column if not exists last_operation_id text,
  add column if not exists last_device_id text;

create index if not exists erp_entity_changes_state_revision_v703_idx
on public.erp_entity_changes (state_id, revision, id);

create index if not exists erp_entity_records_state_collection_v703_idx
on public.erp_entity_records (state_id, collection, deleted, updated_at desc);

create index if not exists erp_entity_records_bill_factory_out_v703_idx
on public.erp_entity_records (state_id, collection, record_id)
where deleted = false;

create index if not exists erp_entity_operations_state_saved_v703_idx
on public.erp_entity_operations (state_id, saved_at desc);

alter table public.erp_entity_meta enable row level security;
alter table public.erp_entity_records enable row level security;
alter table public.erp_entity_changes enable row level security;
alter table public.erp_entity_operations enable row level security;
alter table public.erp_serial_counters enable row level security;
alter table public.erp_backup_requests enable row level security;
alter table public.erp_sync_signal enable row level security;
alter table public.erp_state_backups enable row level security;

drop policy if exists "Allow ERP sync signal read" on public.erp_sync_signal;
create policy "Allow ERP sync signal read" on public.erp_sync_signal
for select to anon, authenticated using (id = 'khushali-jewells-main');

drop policy if exists "Allow ERP backup read" on public.erp_state_backups;
create policy "Allow ERP backup read" on public.erp_state_backups
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity meta read" on public.erp_entity_meta;
create policy "ERP entity meta read" on public.erp_entity_meta
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity records read" on public.erp_entity_records;
create policy "ERP entity records read" on public.erp_entity_records
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity changes read" on public.erp_entity_changes;
create policy "ERP entity changes read" on public.erp_entity_changes
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity operations read" on public.erp_entity_operations;
create policy "ERP entity operations read" on public.erp_entity_operations
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP serial counters read" on public.erp_serial_counters;
create policy "ERP serial counters read" on public.erp_serial_counters
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP backup requests read" on public.erp_backup_requests;
create policy "ERP backup requests read" on public.erp_backup_requests
for select to anon, authenticated using (state_id = 'khushali-jewells-main');

grant select on public.erp_entity_meta, public.erp_entity_records, public.erp_entity_changes,
  public.erp_entity_operations, public.erp_serial_counters, public.erp_backup_requests,
  public.erp_sync_signal, public.erp_state_backups
to anon, authenticated;

revoke insert, update, delete, truncate on public.erp_entity_meta, public.erp_entity_records,
  public.erp_entity_changes, public.erp_entity_operations, public.erp_serial_counters,
  public.erp_backup_requests from anon, authenticated;

-- Seed normalized records only if the installation has not already been seeded.
do $$
declare
  v_state_id text := 'khushali-jewells-main';
  v_data jsonb;
  v_updated_at timestamptz;
  v_pair record;
begin
  select data, updated_at into v_data, v_updated_at
  from public.erp_state where id = v_state_id;

  if v_data is null then
    raise exception 'ERP state % was not found. No migration was performed.', v_state_id;
  end if;

  insert into public.erp_entity_meta
    (state_id, revision, legacy_revision, minimum_revision, updated_at, app_version, legacy_source_updated_at)
  values
    (v_state_id, 1, 1, 1, v_updated_at, coalesce(v_data ->> 'appVersion', 'unknown'), v_updated_at)
  on conflict (state_id) do nothing;

  if not exists (select 1 from public.erp_entity_records where state_id = v_state_id) then
    for v_pair in select key, value from jsonb_each(v_data)
    loop
      if jsonb_typeof(v_pair.value) = 'array'
         and jsonb_array_length(v_pair.value) > 0
         and not exists (
           select 1 from jsonb_array_elements(v_pair.value) item(value)
           where jsonb_typeof(item.value) <> 'object'
              or nullif(item.value ->> 'id', '') is null
         ) then
        insert into public.erp_entity_records
          (state_id, collection, record_id, data, deleted, revision, updated_at, operation_id)
        select v_state_id, v_pair.key, item.value ->> 'id', item.value, false, 1,
          v_updated_at, 'v703-seed'
        from jsonb_array_elements(v_pair.value) item(value)
        on conflict (state_id, collection, record_id) do nothing;
      else
        insert into public.erp_entity_records
          (state_id, collection, record_id, data, deleted, revision, updated_at, operation_id)
        values
          (v_state_id, '@value', v_pair.key, v_pair.value, false, 1, v_updated_at, 'v703-seed')
        on conflict (state_id, collection, record_id) do nothing;
      end if;
    end loop;
  end if;
end;
$$;

create or replace function public.erp_app_build_v703(p_version text)
returns integer
language sql
immutable
as $$
  select coalesce(nullif(regexp_replace(coalesce(p_version, ''), '[^0-9]', '', 'g'), '')::integer, 0)
$$;

create or replace function public.build_erp_normalized_snapshot_v703(p_state_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
set statement_timeout = '120s'
as $$
declare
  v_snapshot jsonb := '{}'::jsonb;
  v_row record;
begin
  for v_row in
    select record_id, data
    from public.erp_entity_records
    where state_id = p_state_id and collection = '@value' and deleted = false
    order by record_id
  loop
    v_snapshot := jsonb_set(v_snapshot, array[v_row.record_id], coalesce(v_row.data, 'null'::jsonb), true);
  end loop;

  for v_row in
    select collection, jsonb_agg(data order by updated_at, record_id) as items
    from public.erp_entity_records
    where state_id = p_state_id and collection <> '@value' and deleted = false
    group by collection
    order by collection
  loop
    v_snapshot := jsonb_set(v_snapshot, array[v_row.collection], coalesce(v_row.items, '[]'::jsonb), true);
  end loop;
  return v_snapshot;
end;
$$;

-- A v703 browser can temporarily fall back to the compatibility row when its
-- local revision no longer matches. This repair copies that newer, verified row
-- back into normalized storage without deleting either cloud backup.
create or replace function public.reconcile_erp_normalized_from_legacy_v704(
  p_state_id text,
  p_expected_source_updated_at timestamptz,
  p_app_version text
)
returns table (
  repaired boolean,
  current_revision bigint,
  source_updated_at timestamptz,
  bill_count integer
)
language plpgsql
security definer
set search_path = public
set lock_timeout = '15s'
set statement_timeout = '240s'
as $$
declare
  v_data jsonb;
  v_source_updated_at timestamptz;
  v_meta public.erp_entity_meta%rowtype;
  v_pair record;
  v_next_revision bigint;
  v_now timestamptz := clock_timestamp();
  v_suffix text;
  v_normalized_backup_key text;
  v_legacy_backup_key text;
  v_bill_count integer := 0;
begin
  if p_state_id <> 'khushali-jewells-main' then raise exception 'Invalid ERP state identifier'; end if;
  if public.erp_app_build_v703(p_app_version) < 704 then raise exception 'ERP v704 or newer is required'; end if;

  select data, updated_at into v_data, v_source_updated_at
  from public.erp_state
  where id = p_state_id
  for share;

  if v_data is null then raise exception 'ERP compatibility state % was not found', p_state_id; end if;
  if p_expected_source_updated_at is null or v_source_updated_at <> p_expected_source_updated_at then
    raise exception 'ERP compatibility state changed while reconciliation was starting';
  end if;

  select * into v_meta
  from public.erp_entity_meta
  where state_id = p_state_id
  for update;

  if v_meta.state_id is null then raise exception 'ERP normalized metadata % was not found', p_state_id; end if;
  if v_meta.legacy_source_updated_at is not null
     and v_meta.legacy_source_updated_at >= v_source_updated_at then
    if jsonb_typeof(v_data -> 'bills') = 'array' then
      v_bill_count := jsonb_array_length(v_data -> 'bills');
    end if;
    return query select false, v_meta.revision, v_source_updated_at, v_bill_count;
    return;
  end if;

  v_suffix := substr(md5(p_state_id || ':' || v_source_updated_at::text), 1, 16);
  v_normalized_backup_key := 'v704-normalized-before-' || v_suffix;
  v_legacy_backup_key := 'v704-legacy-source-' || v_suffix;

  insert into public.erp_state_backups
    (id, state_id, backup_key, backup_kind, source_version, target_version,
     source_updated_at, profile, data, created_at)
  values
    (md5(p_state_id || ':' || v_normalized_backup_key), p_state_id,
     v_normalized_backup_key, 'manual', coalesce(v_meta.app_version, 'unknown'),
     p_app_version, v_meta.updated_at,
     jsonb_build_object('normalized', true, 'reason', 'before-v704-reconciliation'),
     public.build_erp_normalized_snapshot_v703(p_state_id), v_now)
  on conflict (state_id, backup_key) do nothing;

  insert into public.erp_state_backups
    (id, state_id, backup_key, backup_kind, source_version, target_version,
     source_updated_at, profile, data, created_at)
  values
    (md5(p_state_id || ':' || v_legacy_backup_key), p_state_id,
     v_legacy_backup_key, 'manual', coalesce(v_data ->> 'appVersion', 'unknown'),
     p_app_version, v_source_updated_at,
     jsonb_build_object('normalized', false, 'reason', 'v704-reconciliation-source'),
     v_data, v_now)
  on conflict (state_id, backup_key) do nothing;

  v_next_revision := greatest(coalesce(v_meta.revision, 0), coalesce(v_meta.legacy_revision, 0), 1) + 1;

  delete from public.erp_entity_changes where state_id = p_state_id;
  delete from public.erp_entity_operations where state_id = p_state_id;
  delete from public.erp_entity_records where state_id = p_state_id;

  for v_pair in select key, value from jsonb_each(v_data)
  loop
    if jsonb_typeof(v_pair.value) = 'array'
       and jsonb_array_length(v_pair.value) > 0
       and not exists (
         select 1 from jsonb_array_elements(v_pair.value) item(value)
         where jsonb_typeof(item.value) <> 'object'
            or nullif(item.value ->> 'id', '') is null
       ) then
      insert into public.erp_entity_records
        (state_id, collection, record_id, data, deleted, revision, updated_at, operation_id)
      select p_state_id, v_pair.key, item.value ->> 'id', item.value, false,
        v_next_revision, v_now, 'v704-legacy-reconcile'
      from jsonb_array_elements(v_pair.value) item(value)
      on conflict (state_id, collection, record_id) do nothing;
    else
      insert into public.erp_entity_records
        (state_id, collection, record_id, data, deleted, revision, updated_at, operation_id)
      values
        (p_state_id, '@value', v_pair.key, v_pair.value, false,
         v_next_revision, v_now, 'v704-legacy-reconcile');
    end if;
  end loop;

  update public.erp_entity_meta
  set revision = v_next_revision,
      legacy_revision = v_next_revision,
      minimum_revision = v_next_revision,
      updated_at = v_now,
      app_version = p_app_version,
      legacy_source_updated_at = v_source_updated_at
  where state_id = p_state_id;

  insert into public.erp_sync_signal
    (id, updated_at, app_version, revision, last_operation_id, last_device_id)
  values
    (p_state_id, v_now, p_app_version, 1, 'v704-legacy-reconcile', 'supabase-sql-recovery')
  on conflict (id) do update
  set updated_at = excluded.updated_at,
      app_version = excluded.app_version,
      revision = public.erp_sync_signal.revision + 1,
      last_operation_id = excluded.last_operation_id,
      last_device_id = excluded.last_device_id;

  if jsonb_typeof(v_data -> 'bills') = 'array' then
    v_bill_count := jsonb_array_length(v_data -> 'bills');
  end if;
  return query select true, v_next_revision, v_source_updated_at, v_bill_count;
end;
$$;

-- One-time reconciliation for the state that exists when this migration runs.
select *
from public.reconcile_erp_normalized_from_legacy_v704(
  'khushali-jewells-main',
  (select updated_at from public.erp_state where id = 'khushali-jewells-main'),
  'v704'
);

-- Initialize counters above every number already present in normalized data.
insert into public.erp_serial_counters (state_id, serial_kind, next_value, app_version)
select 'khushali-jewells-main', 'job', greatest(1001, coalesce(max(nullif(substring(data ->> 'jobNumber' from '([0-9]+)$'), '')::bigint), 1000) + 1), 'v703'
from public.erp_entity_records where state_id = 'khushali-jewells-main' and collection = 'orders' and deleted = false
on conflict (state_id, serial_kind) do update set next_value = greatest(public.erp_serial_counters.next_value, excluded.next_value);

insert into public.erp_serial_counters (state_id, serial_kind, next_value, app_version)
select 'khushali-jewells-main', 'production', greatest(1001, coalesce(max(nullif(substring(data ->> 'productionNo' from '([0-9]+)$'), '')::bigint), 1000) + 1), 'v703'
from public.erp_entity_records where state_id = 'khushali-jewells-main' and collection = 'orders' and deleted = false
on conflict (state_id, serial_kind) do update set next_value = greatest(public.erp_serial_counters.next_value, excluded.next_value);

insert into public.erp_serial_counters (state_id, serial_kind, next_value, app_version)
select 'khushali-jewells-main', 'lot', greatest(1, coalesce(max(nullif(substring(data ->> 'number' from '([0-9]+)$'), '')::bigint), 0) + 1), 'v703'
from public.erp_entity_records where state_id = 'khushali-jewells-main' and collection = 'lots' and deleted = false
on conflict (state_id, serial_kind) do update set next_value = greatest(public.erp_serial_counters.next_value, excluded.next_value);

insert into public.erp_serial_counters (state_id, serial_kind, next_value, app_version)
select 'khushali-jewells-main', 'bill', greatest(1, coalesce(max(nullif(substring(data ->> 'billNo' from '([0-9]+)$'), '')::bigint), 0) + 1), 'v703'
from public.erp_entity_records where state_id = 'khushali-jewells-main' and collection = 'bills' and deleted = false
on conflict (state_id, serial_kind) do update set next_value = greatest(public.erp_serial_counters.next_value, excluded.next_value);

create or replace function public.reserve_erp_serials_v703(
  p_state_id text,
  p_kind text,
  p_count integer,
  p_device_id text,
  p_app_version text
)
returns table (start_serial bigint, end_serial bigint, reserved_count integer)
language plpgsql
security definer
set search_path = public
set lock_timeout = '8s'
set statement_timeout = '15s'
as $$
declare
  v_start bigint;
  v_count integer := greatest(1, least(coalesce(p_count, 1), 1000));
begin
  if p_state_id <> 'khushali-jewells-main' then raise exception 'Invalid ERP state identifier'; end if;
  if p_kind not in ('job', 'production', 'lot', 'bill') then raise exception 'Invalid ERP serial kind'; end if;
  if public.erp_app_build_v703(p_app_version) < 703 then raise exception 'ERP v703 or newer is required'; end if;

  insert into public.erp_serial_counters (state_id, serial_kind, next_value, app_version)
  values (p_state_id, p_kind, case when p_kind in ('job', 'production') then 1001 else 1 end, p_app_version)
  on conflict (state_id, serial_kind) do nothing;

  select next_value into v_start
  from public.erp_serial_counters
  where state_id = p_state_id and serial_kind = p_kind
  for update;

  update public.erp_serial_counters
  set next_value = v_start + v_count,
      updated_at = clock_timestamp(),
      last_device_id = nullif(p_device_id, ''),
      app_version = p_app_version
  where state_id = p_state_id and serial_kind = p_kind;

  return query select v_start, v_start + v_count - 1, v_count;
end;
$$;

create or replace function public.apply_erp_entity_changes_v703(
  p_state_id text,
  p_expected_revision bigint,
  p_operation_id text,
  p_device_id text,
  p_user_name text,
  p_app_version text,
  p_changes jsonb,
  p_backup_key text default null
)
returns table (
  saved boolean,
  current_revision bigint,
  legacy_revision bigint,
  current_updated_at timestamptz,
  duplicate_operation boolean,
  signal_revision bigint
)
language plpgsql
security definer
set search_path = public
set lock_timeout = '8s'
set statement_timeout = '55s'
as $$
declare
  v_meta public.erp_entity_meta%rowtype;
  v_next_revision bigint;
  v_now timestamptz := clock_timestamp();
  v_change jsonb;
  v_collection text;
  v_record_id text;
  v_operation text;
  v_record_data jsonb;
  v_signal_revision bigint := 0;
  v_operation_id text := nullif(trim(coalesce(p_operation_id, '')), '');
begin
  if p_state_id <> 'khushali-jewells-main' then raise exception 'Invalid ERP state identifier'; end if;
  if v_operation_id is null then raise exception 'Operation ID is required'; end if;
  if public.erp_app_build_v703(p_app_version) < 703 then raise exception 'ERP v703 or newer is required'; end if;

  select * into v_meta from public.erp_entity_meta where state_id = p_state_id for update;
  if v_meta.state_id is null then
    return query select false, 0::bigint, 0::bigint, null::timestamptz, false, 0::bigint;
    return;
  end if;

  if exists (select 1 from public.erp_entity_operations where state_id = p_state_id and operation_id = v_operation_id) then
    select o.revision, o.legacy_revision, o.saved_at
    into v_next_revision, v_meta.legacy_revision, v_now
    from public.erp_entity_operations o
    where o.state_id = p_state_id and o.operation_id = v_operation_id;
    select coalesce(revision, 0) into v_signal_revision from public.erp_sync_signal where id = p_state_id;
    return query select true, v_next_revision, v_meta.legacy_revision, v_now, true, coalesce(v_signal_revision, 0);
    return;
  end if;

  if v_meta.revision <> coalesce(p_expected_revision, -1) then
    return query select false, v_meta.revision, v_meta.legacy_revision, v_meta.updated_at, false, 0::bigint;
    return;
  end if;

  if nullif(trim(coalesce(p_backup_key, '')), '') is not null then
    insert into public.erp_backup_requests (state_id, backup_key, app_version)
    values (p_state_id, p_backup_key, p_app_version)
    on conflict (state_id, backup_key) do nothing;

    if not exists (
      select 1 from public.erp_state_backups
      where state_id = p_state_id and backup_key = p_backup_key
    ) then
      insert into public.erp_state_backups
        (id, state_id, backup_key, backup_kind, source_version, target_version,
         source_updated_at, profile, data, created_at)
      values
        (md5(p_state_id || ':' || p_backup_key), p_state_id, p_backup_key,
         case when p_backup_key like 'version-%' then 'version-upgrade' else 'daily' end,
         coalesce(nullif(v_meta.app_version, ''), 'unknown'), p_app_version,
         v_meta.updated_at,
         jsonb_build_object('normalized', true, 'createdBy', coalesce(nullif(p_user_name, ''), 'ERP User')),
         public.build_erp_normalized_snapshot_v703(p_state_id), v_now)
      on conflict (state_id, backup_key) do nothing;
    end if;

    update public.erp_backup_requests
    set status = 'complete', completed_at = v_now, error_detail = null
    where state_id = p_state_id and backup_key = p_backup_key;
  end if;

  v_next_revision := v_meta.revision + 1;

  for v_change in select value from jsonb_array_elements(coalesce(p_changes -> 'arrays', '[]'::jsonb))
  loop
    v_collection := nullif(v_change ->> 'collection', '');
    v_record_id := nullif(v_change ->> 'recordId', '');
    v_operation := case when v_change ->> 'operation' = 'delete' then 'delete' else 'upsert' end;
    v_record_data := v_change -> 'data';
    if v_collection is null or v_record_id is null then continue; end if;

    insert into public.erp_entity_records
      (state_id, collection, record_id, data, deleted, revision, updated_at, operation_id)
    values
      (p_state_id, v_collection, v_record_id,
       case when v_operation = 'delete' then null else v_record_data end,
       v_operation = 'delete', v_next_revision, v_now, v_operation_id)
    on conflict (state_id, collection, record_id) do update
    set data = excluded.data, deleted = excluded.deleted, revision = excluded.revision,
        updated_at = excluded.updated_at, operation_id = excluded.operation_id;

    insert into public.erp_entity_changes
      (state_id, revision, collection, record_id, operation, data, updated_at,
       operation_id, device_id, user_name, app_version)
    values
      (p_state_id, v_next_revision, v_collection, v_record_id, v_operation,
       case when v_operation = 'delete' then null else v_record_data end,
       v_now, v_operation_id, nullif(p_device_id, ''), nullif(p_user_name, ''), p_app_version);
  end loop;

  for v_change in select value from jsonb_array_elements(coalesce(p_changes -> 'values', '[]'::jsonb))
  loop
    v_record_id := nullif(v_change ->> 'key', '');
    v_operation := case when v_change ->> 'operation' = 'delete' then 'delete' else 'upsert' end;
    v_record_data := v_change -> 'data';
    if v_record_id is null then continue; end if;

    insert into public.erp_entity_records
      (state_id, collection, record_id, data, deleted, revision, updated_at, operation_id)
    values
      (p_state_id, '@value', v_record_id,
       case when v_operation = 'delete' then null else v_record_data end,
       v_operation = 'delete', v_next_revision, v_now, v_operation_id)
    on conflict (state_id, collection, record_id) do update
    set data = excluded.data, deleted = excluded.deleted, revision = excluded.revision,
        updated_at = excluded.updated_at, operation_id = excluded.operation_id;

    insert into public.erp_entity_changes
      (state_id, revision, collection, record_id, operation, data, updated_at,
       operation_id, device_id, user_name, app_version)
    values
      (p_state_id, v_next_revision, '@value', v_record_id, v_operation,
       case when v_operation = 'delete' then null else v_record_data end,
       v_now, v_operation_id, nullif(p_device_id, ''), nullif(p_user_name, ''), p_app_version);
  end loop;

  update public.erp_entity_meta
  set revision = v_next_revision, updated_at = v_now, app_version = p_app_version
  where state_id = p_state_id;

  insert into public.erp_entity_operations
    (state_id, operation_id, revision, legacy_revision, saved_at, device_id, user_name, app_version)
  values
    (p_state_id, v_operation_id, v_next_revision, v_meta.legacy_revision, v_now,
     nullif(p_device_id, ''), nullif(p_user_name, ''), p_app_version);

  insert into public.erp_sync_signal
    (id, updated_at, app_version, revision, last_operation_id, last_device_id)
  values
    (p_state_id, v_now, p_app_version, 1, v_operation_id, nullif(p_device_id, ''))
  on conflict (id) do update
  set updated_at = excluded.updated_at,
      app_version = excluded.app_version,
      revision = public.erp_sync_signal.revision + 1,
      last_operation_id = excluded.last_operation_id,
      last_device_id = excluded.last_device_id
  returning revision into v_signal_revision;

  if mod(v_next_revision, 250) = 0 then
    delete from public.erp_entity_changes where state_id = p_state_id and updated_at < v_now - interval '180 days';
    delete from public.erp_entity_operations where state_id = p_state_id and saved_at < v_now - interval '180 days';
    update public.erp_entity_meta
    set minimum_revision = coalesce((select min(revision) from public.erp_entity_changes where state_id = p_state_id), v_next_revision)
    where state_id = p_state_id;
  end if;

  return query select true, v_next_revision, v_meta.legacy_revision, v_now, false, coalesce(v_signal_revision, 0);
end;
$$;

create or replace function public.verify_erp_factory_out_v703(p_state_id text, p_bill_ids jsonb)
returns table (all_verified boolean, verified_count integer, current_revision bigint, current_updated_at timestamptz)
language plpgsql
security definer
set search_path = public
set statement_timeout = '15s'
as $$
declare
  v_bill_id text;
  v_bill jsonb;
  v_requested integer := 0;
  v_verified integer := 0;
  v_ledger_count integer := 0;
  v_revision bigint := 0;
  v_updated_at timestamptz;
begin
  if p_state_id <> 'khushali-jewells-main' then raise exception 'Invalid ERP state identifier'; end if;
  for v_bill_id in select distinct value from jsonb_array_elements_text(coalesce(p_bill_ids, '[]'::jsonb))
  loop
    v_requested := v_requested + 1;
    select data into v_bill from public.erp_entity_records
    where state_id = p_state_id and collection = 'bills' and record_id = v_bill_id and deleted = false;
    if v_bill is null or nullif(v_bill ->> 'factoryOutPostedAt', '') is null then continue; end if;
    select count(*) into v_ledger_count
    from public.erp_entity_records
    where state_id = p_state_id and collection = 'factoryLedger' and deleted = false
      and coalesce(data ->> 'sourceType', '') = 'bill'
      and coalesce(data ->> 'sourceId', data ->> 'billId', '') = v_bill_id;
    if v_ledger_count = 1 then v_verified := v_verified + 1; end if;
  end loop;
  select revision, updated_at into v_revision, v_updated_at
  from public.erp_entity_meta where state_id = p_state_id;
  return query select (v_requested > 0 and v_requested = v_verified), v_verified, coalesce(v_revision, 0), v_updated_at;
end;
$$;

create or replace function public.create_erp_normalized_backup_v703(
  p_state_id text,
  p_backup_key text,
  p_backup_kind text,
  p_user_name text,
  p_app_version text
)
returns table (saved boolean, backup_key text, created_at timestamptz)
language plpgsql
security definer
set search_path = public
set statement_timeout = '120s'
as $$
declare
  v_snapshot jsonb;
  v_now timestamptz := clock_timestamp();
  v_key text := nullif(trim(coalesce(p_backup_key, '')), '');
begin
  if p_state_id <> 'khushali-jewells-main' then raise exception 'Invalid ERP state identifier'; end if;
  if v_key is null then raise exception 'Backup key is required'; end if;
  if public.erp_app_build_v703(p_app_version) < 703 then raise exception 'ERP v703 or newer is required'; end if;
  if exists (select 1 from public.erp_state_backups where state_id = p_state_id and backup_key = v_key) then
    return query select true, v_key, (select b.created_at from public.erp_state_backups b where b.state_id = p_state_id and b.backup_key = v_key limit 1);
    return;
  end if;
  v_snapshot := public.build_erp_normalized_snapshot_v703(p_state_id);
  insert into public.erp_state_backups
    (id, state_id, backup_key, backup_kind, source_version, target_version,
     source_updated_at, profile, data, created_at)
  values
    (md5(p_state_id || ':' || v_key), p_state_id, v_key,
     case when p_backup_kind in ('version-upgrade', 'daily', 'manual') then p_backup_kind else 'daily' end,
     p_app_version, p_app_version, v_now,
     jsonb_build_object('createdBy', coalesce(nullif(p_user_name, ''), 'ERP User'), 'normalized', true),
     v_snapshot, v_now)
  on conflict (state_id, backup_key) do nothing;
  update public.erp_backup_requests
  set status = 'complete', completed_at = v_now, error_detail = null
  where state_id = p_state_id and backup_key = v_key;
  return query select true, v_key, v_now;
exception when others then
  update public.erp_backup_requests
  set status = 'failed', error_detail = left(sqlerrm, 500)
  where state_id = p_state_id and backup_key = v_key;
  raise;
end;
$$;

-- v702 compatibility: an already-open older tab uses the same payload shape.
-- Route it through the normalized writer so its work is not stranded and the
-- large legacy erp_state document is not rewritten.
create or replace function public.apply_erp_entity_changes_v666(
  p_state_id text,
  p_expected_revision bigint,
  p_operation_id text,
  p_device_id text,
  p_user_name text,
  p_app_version text,
  p_changes jsonb,
  p_backup_key text default null
)
returns table (
  saved boolean,
  current_revision bigint,
  legacy_revision bigint,
  current_updated_at timestamptz,
  duplicate_operation boolean,
  signal_revision bigint
)
language sql
security definer
set search_path = public
set statement_timeout = '55s'
as $$
  select * from public.apply_erp_entity_changes_v703(
    p_state_id,
    p_expected_revision,
    p_operation_id,
    p_device_id,
    p_user_name,
    'v703',
    p_changes,
    p_backup_key
  )
$$;

-- Keep the exact v640 writer available only as a compatibility drain for an
-- already-open v703 tab. v704 itself never falls back to it for routine edits.
do $$
declare
  v_function record;
begin
  for v_function in
    select p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'save_erp_state_atomic_v640'
  loop
    execute format('grant execute on function %s to anon, authenticated', v_function.signature);
  end loop;
end;
$$;

grant usage on schema public to anon, authenticated;
revoke all on function public.reserve_erp_serials_v703(text, text, integer, text, text) from public;
revoke all on function public.apply_erp_entity_changes_v703(text, bigint, text, text, text, text, jsonb, text) from public;
revoke all on function public.verify_erp_factory_out_v703(text, jsonb) from public;
revoke all on function public.create_erp_normalized_backup_v703(text, text, text, text, text) from public;
revoke all on function public.reconcile_erp_normalized_from_legacy_v704(text, timestamptz, text) from public;

grant execute on function public.reserve_erp_serials_v703(text, text, integer, text, text) to anon, authenticated;
grant execute on function public.apply_erp_entity_changes_v703(text, bigint, text, text, text, text, jsonb, text) to anon, authenticated;
grant execute on function public.apply_erp_entity_changes_v666(text, bigint, text, text, text, text, jsonb, text) to anon, authenticated;
grant execute on function public.verify_erp_factory_out_v703(text, jsonb) to anon, authenticated;
grant execute on function public.create_erp_normalized_backup_v703(text, text, text, text, text) to anon, authenticated;
grant execute on function public.reconcile_erp_normalized_from_legacy_v704(text, timestamptz, text) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'erp_sync_signal'
  ) then
    alter publication supabase_realtime add table public.erp_sync_signal;
  end if;
end;
$$;

analyze public.erp_entity_meta;
analyze public.erp_entity_records;
analyze public.erp_entity_changes;
analyze public.erp_entity_operations;
analyze public.erp_serial_counters;
notify pgrst, 'reload schema';
notify pgrst, 'reload config';

select state_id, revision, legacy_revision, minimum_revision, updated_at, app_version,
  legacy_source_updated_at
from public.erp_entity_meta where state_id = 'khushali-jewells-main';

select
  has_function_privilege(
    'anon',
    'public.apply_erp_entity_changes_v703(text,bigint,text,text,text,text,jsonb,text)',
    'EXECUTE'
  ) as anon_v703_execute,
  has_function_privilege(
    'authenticated',
    'public.apply_erp_entity_changes_v703(text,bigint,text,text,text,text,jsonb,text)',
    'EXECUTE'
  ) as authenticated_v703_execute,
  has_function_privilege(
    'anon',
    'public.reconcile_erp_normalized_from_legacy_v704(text,timestamptz,text)',
    'EXECUTE'
  ) as anon_v704_reconcile,
  case
    when to_regprocedure('public.save_erp_state_atomic_v640(text,jsonb,timestamptz,timestamptz,text,text,text,text,jsonb,text,text,text)') is null then false
    else has_function_privilege(
      'anon',
      'public.save_erp_state_atomic_v640(text,jsonb,timestamptz,timestamptz,text,text,text,text,jsonb,text,text,text)',
      'EXECUTE'
    )
  end as anon_v640_compatibility_execute;

select serial_kind, next_value, updated_at
from public.erp_serial_counters where state_id = 'khushali-jewells-main'
order by serial_kind;
