-- KHUSHALI JEWELLS ERP v666 - INCREMENTAL MULTI-DEVICE SYNC
-- Run once in Supabase Dashboard > SQL Editor after SUPABASE-ADVANCED-SYNC-v640.sql.
-- Non-destructive: existing public.erp_state data is preserved and remains a compatibility copy.

create table if not exists public.erp_entity_meta (
  state_id text primary key,
  revision bigint not null default 0,
  legacy_revision bigint not null default 0,
  minimum_revision bigint not null default 0,
  updated_at timestamptz not null default clock_timestamp(),
  app_version text not null default 'unknown'
);

create table if not exists public.erp_entity_records (
  state_id text not null,
  collection text not null,
  record_id text not null,
  data jsonb,
  deleted boolean not null default false,
  revision bigint not null default 0,
  updated_at timestamptz not null default clock_timestamp(),
  operation_id text,
  primary key (state_id, collection, record_id)
);

create table if not exists public.erp_entity_changes (
  id bigint generated by default as identity primary key,
  state_id text not null,
  revision bigint not null,
  collection text not null,
  record_id text not null,
  operation text not null check (operation in ('upsert', 'delete')),
  data jsonb,
  updated_at timestamptz not null default clock_timestamp(),
  operation_id text,
  device_id text,
  user_name text,
  app_version text not null default 'unknown',
  unique (state_id, revision, collection, record_id)
);

create table if not exists public.erp_entity_operations (
  state_id text not null,
  operation_id text not null,
  revision bigint not null,
  legacy_revision bigint not null default 0,
  saved_at timestamptz not null default clock_timestamp(),
  device_id text,
  user_name text,
  app_version text not null default 'unknown',
  primary key (state_id, operation_id)
);

create index if not exists erp_entity_changes_state_revision_idx
on public.erp_entity_changes (state_id, revision, id);

create index if not exists erp_entity_records_state_collection_idx
on public.erp_entity_records (state_id, collection, deleted, updated_at desc);

alter table public.erp_entity_meta enable row level security;
alter table public.erp_entity_records enable row level security;
alter table public.erp_entity_changes enable row level security;
alter table public.erp_entity_operations enable row level security;

drop policy if exists "ERP entity meta read" on public.erp_entity_meta;
create policy "ERP entity meta read" on public.erp_entity_meta
for select to anon, authenticated
using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity records read" on public.erp_entity_records;
create policy "ERP entity records read" on public.erp_entity_records
for select to anon, authenticated
using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity changes read" on public.erp_entity_changes;
create policy "ERP entity changes read" on public.erp_entity_changes
for select to anon, authenticated
using (state_id = 'khushali-jewells-main');

drop policy if exists "ERP entity operations read" on public.erp_entity_operations;
create policy "ERP entity operations read" on public.erp_entity_operations
for select to anon, authenticated
using (state_id = 'khushali-jewells-main');

grant select on public.erp_entity_meta, public.erp_entity_records, public.erp_entity_changes, public.erp_entity_operations to anon, authenticated;
revoke insert, update, delete, truncate on public.erp_entity_meta, public.erp_entity_records, public.erp_entity_changes, public.erp_entity_operations from anon, authenticated;

-- Seed normalized current records from the existing, verified compatibility row.
do $$
declare
  v_state_id text := 'khushali-jewells-main';
  v_data jsonb;
  v_updated_at timestamptz;
  v_pair record;
begin
  select data, updated_at into v_data, v_updated_at
  from public.erp_state
  where id = v_state_id;

  if v_data is null then
    raise exception 'ERP state % was not found. No migration was performed.', v_state_id;
  end if;

  insert into public.erp_entity_meta (state_id, revision, legacy_revision, minimum_revision, updated_at, app_version)
  values (v_state_id, 1, 1, 1, v_updated_at, coalesce(v_data ->> 'appVersion', 'unknown'))
  on conflict (state_id) do nothing;

  if not exists (select 1 from public.erp_entity_records where state_id = v_state_id) then
    for v_pair in select key, value from jsonb_each(v_data)
    loop
      if jsonb_typeof(v_pair.value) = 'array'
         and jsonb_array_length(v_pair.value) > 0
         and not exists (
           select 1
           from jsonb_array_elements(v_pair.value) as item(value)
           where jsonb_typeof(item.value) <> 'object'
              or nullif(item.value ->> 'id', '') is null
         ) then
        insert into public.erp_entity_records (
          state_id, collection, record_id, data, deleted, revision, updated_at, operation_id
        )
        select v_state_id, v_pair.key, item.value ->> 'id', item.value, false, 1, v_updated_at, 'v666-seed'
        from jsonb_array_elements(v_pair.value) as item(value)
        on conflict (state_id, collection, record_id) do nothing;
      else
        insert into public.erp_entity_records (
          state_id, collection, record_id, data, deleted, revision, updated_at, operation_id
        ) values (
          v_state_id, '@value', v_pair.key, v_pair.value, false, 1, v_updated_at, 'v666-seed'
        )
        on conflict (state_id, collection, record_id) do nothing;
      end if;
    end loop;
  end if;
end;
$$;

-- Older ERP builds still write the compatibility row. Record that separately so
-- v666 clients perform one protected full refresh instead of missing old-client work.
create or replace function public.track_erp_legacy_state_write_v666()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(current_setting('app.erp_incremental_write', true), '') <> '1' then
    insert into public.erp_entity_meta (
      state_id, revision, legacy_revision, minimum_revision, updated_at, app_version
    ) values (
      new.id, 1, 1, 1, new.updated_at, coalesce(new.data ->> 'appVersion', 'unknown')
    )
    on conflict (state_id) do update
    set revision = public.erp_entity_meta.revision + 1,
        legacy_revision = public.erp_entity_meta.legacy_revision + 1,
        updated_at = excluded.updated_at,
        app_version = excluded.app_version;
  end if;
  return new;
end;
$$;

drop trigger if exists erp_state_track_legacy_write_v666 on public.erp_state;
create trigger erp_state_track_legacy_write_v666
after insert or update of data, updated_at on public.erp_state
for each row execute function public.track_erp_legacy_state_write_v666();

create or replace function public.apply_erp_entity_changes_v666(
  p_state_id text,
  p_expected_revision bigint,
  p_operation_id text,
  p_device_id text,
  p_user_name text,
  p_app_version text,
  p_changes jsonb,
  p_backup_key text default null
)
returns table (
  saved boolean,
  current_revision bigint,
  legacy_revision bigint,
  current_updated_at timestamptz,
  duplicate_operation boolean,
  signal_revision bigint
)
language plpgsql
security definer
set search_path = public
set lock_timeout = '8s'
set statement_timeout = '55s'
as $$
declare
  v_meta public.erp_entity_meta%rowtype;
  v_legacy jsonb;
  v_legacy_updated_at timestamptz;
  v_next_revision bigint;
  v_now timestamptz := clock_timestamp();
  v_change jsonb;
  v_collection text;
  v_record_id text;
  v_operation text;
  v_record_data jsonb;
  v_array jsonb;
  v_signal_revision bigint := 0;
  v_operation_id text := nullif(trim(coalesce(p_operation_id, '')), '');
begin
  if p_state_id <> 'khushali-jewells-main' then
    raise exception 'Invalid ERP state identifier';
  end if;
  if v_operation_id is null then
    raise exception 'Operation ID is required';
  end if;

  select data, updated_at into v_legacy, v_legacy_updated_at
  from public.erp_state
  where id = p_state_id
  for update;

  if v_legacy is null then
    return query select false, 0::bigint, 0::bigint, null::timestamptz, false, 0::bigint;
    return;
  end if;

  select * into v_meta
  from public.erp_entity_meta
  where state_id = p_state_id
  for update;

  if exists (
    select 1 from public.erp_entity_operations
    where state_id = p_state_id and operation_id = v_operation_id
  ) then
    select o.revision, o.legacy_revision, o.saved_at
    into v_next_revision, v_meta.legacy_revision, v_now
    from public.erp_entity_operations o
    where o.state_id = p_state_id and o.operation_id = v_operation_id;
    select coalesce(revision, 0) into v_signal_revision
    from public.erp_sync_signal where id = p_state_id;
    return query select true, v_next_revision, v_meta.legacy_revision, v_now, true, coalesce(v_signal_revision, 0);
    return;
  end if;

  if v_meta.state_id is null or v_meta.revision <> coalesce(p_expected_revision, -1) then
    return query select false, coalesce(v_meta.revision, 0), coalesce(v_meta.legacy_revision, 0), coalesce(v_meta.updated_at, v_legacy_updated_at), false, 0::bigint;
    return;
  end if;

  if nullif(trim(coalesce(p_backup_key, '')), '') is not null then
    insert into public.erp_state_backups (
      id, state_id, backup_key, backup_kind, source_version, target_version,
      source_updated_at, profile, data, created_at
    ) values (
      md5(p_state_id || ':' || p_backup_key), p_state_id, p_backup_key,
      case when p_backup_key like 'version-%' then 'version-upgrade' else 'daily' end,
      coalesce(v_legacy ->> 'appVersion', 'unknown'), coalesce(nullif(p_app_version, ''), 'unknown'),
      v_legacy_updated_at, '{}'::jsonb, v_legacy, v_now
    ) on conflict (state_id, backup_key) do nothing;
  end if;

  v_next_revision := v_meta.revision + 1;

  for v_change in select value from jsonb_array_elements(coalesce(p_changes -> 'arrays', '[]'::jsonb))
  loop
    v_collection := nullif(v_change ->> 'collection', '');
    v_record_id := nullif(v_change ->> 'recordId', '');
    v_operation := case when v_change ->> 'operation' = 'delete' then 'delete' else 'upsert' end;
    v_record_data := v_change -> 'data';
    if v_collection is null or v_record_id is null then continue; end if;

    insert into public.erp_entity_records (
      state_id, collection, record_id, data, deleted, revision, updated_at, operation_id
    ) values (
      p_state_id, v_collection, v_record_id,
      case when v_operation = 'delete' then null else v_record_data end,
      v_operation = 'delete', v_next_revision, v_now, v_operation_id
    ) on conflict (state_id, collection, record_id) do update
    set data = excluded.data, deleted = excluded.deleted, revision = excluded.revision,
        updated_at = excluded.updated_at, operation_id = excluded.operation_id;

    insert into public.erp_entity_changes (
      state_id, revision, collection, record_id, operation, data, updated_at,
      operation_id, device_id, user_name, app_version
    ) values (
      p_state_id, v_next_revision, v_collection, v_record_id, v_operation,
      case when v_operation = 'delete' then null else v_record_data end,
      v_now, v_operation_id, nullif(p_device_id, ''), nullif(p_user_name, ''), coalesce(nullif(p_app_version, ''), 'unknown')
    );

    v_array := coalesce(v_legacy -> v_collection, '[]'::jsonb);
    if jsonb_typeof(v_array) <> 'array' then v_array := '[]'::jsonb; end if;
    select coalesce(jsonb_agg(item.value order by item.ordinality), '[]'::jsonb)
    into v_array
    from jsonb_array_elements(v_array) with ordinality as item(value, ordinality)
    where coalesce(item.value ->> 'id', '') <> v_record_id;
    if v_operation = 'upsert' then
      v_array := v_array || jsonb_build_array(v_record_data);
    end if;
    v_legacy := jsonb_set(v_legacy, array[v_collection], v_array, true);
  end loop;

  for v_change in select value from jsonb_array_elements(coalesce(p_changes -> 'values', '[]'::jsonb))
  loop
    v_record_id := nullif(v_change ->> 'key', '');
    v_operation := case when v_change ->> 'operation' = 'delete' then 'delete' else 'upsert' end;
    v_record_data := v_change -> 'data';
    if v_record_id is null then continue; end if;

    insert into public.erp_entity_records (
      state_id, collection, record_id, data, deleted, revision, updated_at, operation_id
    ) values (
      p_state_id, '@value', v_record_id,
      case when v_operation = 'delete' then null else v_record_data end,
      v_operation = 'delete', v_next_revision, v_now, v_operation_id
    ) on conflict (state_id, collection, record_id) do update
    set data = excluded.data, deleted = excluded.deleted, revision = excluded.revision,
        updated_at = excluded.updated_at, operation_id = excluded.operation_id;

    insert into public.erp_entity_changes (
      state_id, revision, collection, record_id, operation, data, updated_at,
      operation_id, device_id, user_name, app_version
    ) values (
      p_state_id, v_next_revision, '@value', v_record_id, v_operation,
      case when v_operation = 'delete' then null else v_record_data end,
      v_now, v_operation_id, nullif(p_device_id, ''), nullif(p_user_name, ''), coalesce(nullif(p_app_version, ''), 'unknown')
    );

    if v_operation = 'delete' then v_legacy := v_legacy - v_record_id;
    else v_legacy := jsonb_set(v_legacy, array[v_record_id], v_record_data, true);
    end if;
  end loop;

  v_legacy := jsonb_set(v_legacy, '{appVersion}', to_jsonb(coalesce(nullif(p_app_version, ''), 'v666')), true);
  v_legacy := jsonb_set(v_legacy, '{appBuild}', to_jsonb(coalesce(nullif(regexp_replace(p_app_version, '[^0-9]', '', 'g'), '')::integer, 666)), true);
  v_legacy := jsonb_set(v_legacy, '{syncSchemaVersion}', to_jsonb(coalesce(nullif(regexp_replace(p_app_version, '[^0-9]', '', 'g'), '')::integer, 666)), true);
  v_legacy := jsonb_set(v_legacy, '{lastSavedAt}', to_jsonb(v_now::text), true);
  v_legacy := jsonb_set(v_legacy, '{syncMeta}', jsonb_build_object(
    'lastOperationId', v_operation_id, 'lastDeviceId', coalesce(p_device_id, ''),
    'lastUser', coalesce(p_user_name, ''), 'lastSavedAt', v_now, 'appVersion', coalesce(p_app_version, 'v666')
  ), true);

  perform set_config('app.erp_incremental_write', '1', true);
  update public.erp_state set data = v_legacy, updated_at = v_now where id = p_state_id;

  update public.erp_entity_meta
  set revision = v_next_revision, updated_at = v_now,
      app_version = coalesce(nullif(p_app_version, ''), 'unknown')
  where state_id = p_state_id;

  insert into public.erp_entity_operations (
    state_id, operation_id, revision, legacy_revision, saved_at, device_id, user_name, app_version
  ) values (
    p_state_id, v_operation_id, v_next_revision, v_meta.legacy_revision, v_now,
    nullif(p_device_id, ''), nullif(p_user_name, ''), coalesce(nullif(p_app_version, ''), 'unknown')
  );

  delete from public.erp_entity_changes
  where state_id = p_state_id and updated_at < v_now - interval '180 days';
  delete from public.erp_entity_operations
  where state_id = p_state_id and saved_at < v_now - interval '180 days';

  update public.erp_entity_meta
  set minimum_revision = coalesce((
    select min(revision) from public.erp_entity_changes where state_id = p_state_id
  ), v_next_revision)
  where state_id = p_state_id;

  select coalesce(revision, 0) into v_signal_revision
  from public.erp_sync_signal where id = p_state_id;

  return query select true, v_next_revision, v_meta.legacy_revision, v_now, false, coalesce(v_signal_revision, 0);
end;
$$;

revoke all on function public.apply_erp_entity_changes_v666(text, bigint, text, text, text, text, jsonb, text) from public;
grant execute on function public.apply_erp_entity_changes_v666(text, bigint, text, text, text, text, jsonb, text) to anon, authenticated;

-- Direct anonymous writes are no longer needed after the exact-save RPCs are installed.
-- Reads remain available to support protected recovery and compatibility loading.
revoke insert, update, delete, truncate on public.erp_state from anon, authenticated;
drop policy if exists "Allow ERP write" on public.erp_state;
drop policy if exists "Allow ERP read" on public.erp_state;
create policy "Allow ERP main-state read" on public.erp_state
for select to anon, authenticated
using (id = 'khushali-jewells-main');

analyze public.erp_entity_meta;
analyze public.erp_entity_records;
analyze public.erp_entity_changes;
analyze public.erp_entity_operations;
notify pgrst, 'reload schema';

select state_id, revision, legacy_revision, minimum_revision, updated_at, app_version
from public.erp_entity_meta
where state_id = 'khushali-jewells-main';
